name: APP Deployment to s3 bucket

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --silent

      - name: Build react app
        run: npm run build

      - name: List files
        run: ls -al dist

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync build s3://react-app-ferrari-bucket --delete